"""add_career_and_activities_fields_to_profile

Revision ID: 2896b48beb58
Revises: f02e805e59d3
Create Date: 2025-11-05 05:02:44.199423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2896b48beb58'
down_revision: Union[str, None] = 'f02e805e59d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admissions_data_unique', 'admissions_data', type_='unique')
    op.add_column('user_profiles', sa.Column('career_goals', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('volunteer_hours', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('extracurriculars', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('work_experience', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('honors_awards', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('user_profiles', sa.Column('skills', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('user_profiles', 'gpa_scale',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'gpa_scale',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('user_profiles', 'skills')
    op.drop_column('user_profiles', 'honors_awards')
    op.drop_column('user_profiles', 'work_experience')
    op.drop_column('user_profiles', 'extracurriculars')
    op.drop_column('user_profiles', 'volunteer_hours')
    op.drop_column('user_profiles', 'career_goals')
    op.create_unique_constraint('admissions_data_unique', 'admissions_data', ['ipeds_id', 'academic_year'])
    # ### end Alembic commands ###
