"""simplified admissions table

Revision ID: 353dd1fda711
Revises: 453d14b234de
Create Date: 2025-11-03 13:42:35.789635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '353dd1fda711'
down_revision: Union[str, None] = '453d14b234de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admissions_data_act_composite_50th', table_name='admissions_data')
    op.drop_column('admissions_data', 'act_english_25th')
    op.drop_column('admissions_data', 'act_composite_50th')
    op.drop_column('admissions_data', 'act_math_25th')
    op.drop_column('admissions_data', 'act_composite_75th')
    op.drop_column('admissions_data', 'updated_at')
    op.drop_column('admissions_data', 'act_english_75th')
    op.drop_column('admissions_data', 'act_composite_25th')
    op.drop_column('admissions_data', 'act_math_75th')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions_data', sa.Column('act_math_75th', sa.INTEGER(), autoincrement=False, nullable=True, comment='ACT Math 75th percentile'))
    op.add_column('admissions_data', sa.Column('act_composite_25th', sa.INTEGER(), autoincrement=False, nullable=True, comment='ACT Composite 25th percentile'))
    op.add_column('admissions_data', sa.Column('act_english_75th', sa.INTEGER(), autoincrement=False, nullable=True, comment='ACT English 75th percentile'))
    op.add_column('admissions_data', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record last update timestamp'))
    op.add_column('admissions_data', sa.Column('act_composite_75th', sa.INTEGER(), autoincrement=False, nullable=True, comment='ACT Composite 75th percentile'))
    op.add_column('admissions_data', sa.Column('act_math_25th', sa.INTEGER(), autoincrement=False, nullable=True, comment='ACT Math 25th percentile'))
    op.add_column('admissions_data', sa.Column('act_composite_50th', sa.INTEGER(), autoincrement=False, nullable=True, comment='ACT Composite 50th percentile (median)'))
    op.add_column('admissions_data', sa.Column('act_english_25th', sa.INTEGER(), autoincrement=False, nullable=True, comment='ACT English 25th percentile'))
    op.create_index('ix_admissions_data_act_composite_50th', 'admissions_data', ['act_composite_50th'], unique=False)
    # ### end Alembic commands ###
