"""Create scholarship tables

Revision ID: 3cf8f51a8e97
Revises: d04a0794821d
Create Date: 2025-08-25 05:01:52.082653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cf8f51a8e97'
down_revision: Union[str, None] = 'd04a0794821d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('high_school_name', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('sat_score', sa.Integer(), nullable=True),
    sa.Column('act_score', sa.Integer(), nullable=True),
    sa.Column('intended_major', sa.String(length=255), nullable=True),
    sa.Column('academic_interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('career_goals', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('extracurricular_activities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('volunteer_experience', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('volunteer_hours', sa.Integer(), nullable=True),
    sa.Column('work_experience', sa.JSON(), nullable=True),
    sa.Column('ethnicity', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('first_generation_college', sa.Boolean(), nullable=True),
    sa.Column('household_income_range', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('preferred_college_size', sa.String(length=50), nullable=True),
    sa.Column('preferred_college_location', sa.String(length=100), nullable=True),
    sa.Column('college_application_status', sa.String(length=50), nullable=True),
    sa.Column('personal_statement', sa.Text(), nullable=True),
    sa.Column('leadership_experience', sa.Text(), nullable=True),
    sa.Column('challenges_overcome', sa.Text(), nullable=True),
    sa.Column('scholarship_types_interested', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('application_deadline_preference', sa.String(length=50), nullable=True),
    sa.Column('languages_spoken', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('special_talents', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
