"""getting relevant tuition data

Revision ID: 3d829ff1a67c
Revises: 74d4d6720607
Create Date: 2025-09-23 03:38:28.017933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d829ff1a67c'
down_revision: Union[str, None] = '74d4d6720607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuition_data', sa.Column('room_board_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON breakdown of room/board costs: {"housing": 9346, "meals": 5358, "total": 14704}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tuition_data', 'room_board_breakdown')
    # ### end Alembic commands ###
