"""Add s2023_is table

Revision ID: 3e6eeba8f764
Revises: fe3435a26779
Create Date: 2025-09-10 04:21:20.571300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6eeba8f764'
down_revision: Union[str, None] = 'fe3435a26779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s2023_is',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unitid', sa.String(length=10), nullable=False),
    sa.Column('total_faculty', sa.Integer(), nullable=False),
    sa.Column('female_faculty_percent', sa.Float(), nullable=False),
    sa.Column('male_faculty_percent', sa.Float(), nullable=False),
    sa.Column('diversity_category', sa.String(length=20), nullable=False),
    sa.Column('faculty_size_category', sa.String(length=20), nullable=False),
    sa.Column('faculty_description', sa.Text(), nullable=False),
    sa.Column('diversity_index', sa.Float(), nullable=False),
    sa.Column('asian_faculty_percent', sa.Float(), nullable=False),
    sa.Column('black_faculty_percent', sa.Float(), nullable=False),
    sa.Column('hispanic_faculty_percent', sa.Float(), nullable=False),
    sa.Column('white_faculty_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s2023_is_id'), 's2023_is', ['id'], unique=False)
    op.create_index(op.f('ix_s2023_is_unitid'), 's2023_is', ['unitid'], unique=True)
    op.drop_index('ix_faculty_metrics_id', table_name='faculty_metrics')
    op.drop_index('ix_faculty_metrics_unitid', table_name='faculty_metrics')
    op.drop_table('faculty_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unitid', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('total_faculty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('female_faculty_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('male_faculty_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('diversity_category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('faculty_size_category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('faculty_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('diversity_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('asian_faculty_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('black_faculty_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hispanic_faculty_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('white_faculty_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='faculty_metrics_pkey')
    )
    op.create_index('ix_faculty_metrics_unitid', 'faculty_metrics', ['unitid'], unique=False)
    op.create_index('ix_faculty_metrics_id', 'faculty_metrics', ['id'], unique=False)
    op.drop_index(op.f('ix_s2023_is_unitid'), table_name='s2023_is')
    op.drop_index(op.f('ix_s2023_is_id'), table_name='s2023_is')
    op.drop_table('s2023_is')
    # ### end Alembic commands ###
