"""updating institutions table

Revision ID: 453d14b234de
Revises: b440136139c6
Create Date: 2025-11-01 12:10:18.738222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453d14b234de'
down_revision: Union[str, None] = 'b440136139c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admissions_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipeds_id', sa.Integer(), nullable=False, comment='IPEDS institution identifier'),
    sa.Column('academic_year', sa.String(length=10), nullable=False, comment='Academic year (e.g., 2023-24)'),
    sa.Column('applications_total', sa.Integer(), nullable=True, comment='Total applications received'),
    sa.Column('admissions_total', sa.Integer(), nullable=True, comment='Total students admitted'),
    sa.Column('enrolled_total', sa.Integer(), nullable=True, comment='Total students enrolled'),
    sa.Column('acceptance_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Acceptance rate as percentage (0-100)'),
    sa.Column('yield_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Yield rate as percentage (0-100)'),
    sa.Column('sat_reading_25th', sa.Integer(), nullable=True, comment='SAT Evidence-Based Reading/Writing 25th percentile'),
    sa.Column('sat_reading_50th', sa.Integer(), nullable=True, comment='SAT Evidence-Based Reading/Writing 50th percentile (median)'),
    sa.Column('sat_reading_75th', sa.Integer(), nullable=True, comment='SAT Evidence-Based Reading/Writing 75th percentile'),
    sa.Column('sat_math_25th', sa.Integer(), nullable=True, comment='SAT Math 25th percentile'),
    sa.Column('sat_math_50th', sa.Integer(), nullable=True, comment='SAT Math 50th percentile (median)'),
    sa.Column('sat_math_75th', sa.Integer(), nullable=True, comment='SAT Math 75th percentile'),
    sa.Column('act_composite_25th', sa.Integer(), nullable=True, comment='ACT Composite 25th percentile'),
    sa.Column('act_composite_50th', sa.Integer(), nullable=True, comment='ACT Composite 50th percentile (median)'),
    sa.Column('act_composite_75th', sa.Integer(), nullable=True, comment='ACT Composite 75th percentile'),
    sa.Column('act_english_25th', sa.Integer(), nullable=True, comment='ACT English 25th percentile'),
    sa.Column('act_english_75th', sa.Integer(), nullable=True, comment='ACT English 75th percentile'),
    sa.Column('act_math_25th', sa.Integer(), nullable=True, comment='ACT Math 25th percentile'),
    sa.Column('act_math_75th', sa.Integer(), nullable=True, comment='ACT Math 75th percentile'),
    sa.Column('percent_submitting_sat', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage of enrolled students who submitted SAT'),
    sa.Column('percent_submitting_act', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage of enrolled students who submitted ACT'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['ipeds_id'], ['institutions.ipeds_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Admissions statistics and test scores by academic year'
    )
    op.create_index(op.f('ix_admissions_data_academic_year'), 'admissions_data', ['academic_year'], unique=False)
    op.create_index(op.f('ix_admissions_data_acceptance_rate'), 'admissions_data', ['acceptance_rate'], unique=False)
    op.create_index(op.f('ix_admissions_data_act_composite_50th'), 'admissions_data', ['act_composite_50th'], unique=False)
    op.create_index(op.f('ix_admissions_data_id'), 'admissions_data', ['id'], unique=False)
    op.create_index(op.f('ix_admissions_data_ipeds_id'), 'admissions_data', ['ipeds_id'], unique=False)
    op.create_index(op.f('ix_admissions_data_sat_math_50th'), 'admissions_data', ['sat_math_50th'], unique=False)
    op.create_table('enrollment_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipeds_id', sa.Integer(), nullable=False, comment='IPEDS institution identifier'),
    sa.Column('academic_year', sa.String(length=10), nullable=False, comment='Academic year (e.g., 2023-24)'),
    sa.Column('total_enrollment', sa.Integer(), nullable=True, comment='Total undergraduate enrollment'),
    sa.Column('full_time_enrollment', sa.Integer(), nullable=True, comment='Full-time undergraduate enrollment'),
    sa.Column('part_time_enrollment', sa.Integer(), nullable=True, comment='Part-time undergraduate enrollment'),
    sa.Column('enrollment_men', sa.Integer(), nullable=True, comment='Number of male students enrolled'),
    sa.Column('enrollment_women', sa.Integer(), nullable=True, comment='Number of female students enrolled'),
    sa.Column('enrollment_in_state', sa.Integer(), nullable=True, comment='Number of in-state students'),
    sa.Column('enrollment_out_of_state', sa.Integer(), nullable=True, comment='Number of out-of-state students'),
    sa.Column('percent_full_time', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage of students enrolled full-time'),
    sa.Column('percent_in_state', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage of students from in-state'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['ipeds_id'], ['institutions.ipeds_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Enrollment statistics by academic year'
    )
    op.create_index(op.f('ix_enrollment_data_academic_year'), 'enrollment_data', ['academic_year'], unique=False)
    op.create_index(op.f('ix_enrollment_data_id'), 'enrollment_data', ['id'], unique=False)
    op.create_index(op.f('ix_enrollment_data_ipeds_id'), 'enrollment_data', ['ipeds_id'], unique=False)
    op.create_index(op.f('ix_enrollment_data_total_enrollment'), 'enrollment_data', ['total_enrollment'], unique=False)
    op.create_table('graduation_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipeds_id', sa.Integer(), nullable=False, comment='IPEDS institution identifier'),
    sa.Column('cohort_year', sa.String(length=10), nullable=False, comment='Starting cohort year (e.g., 2017 for 6-year rate in 2023)'),
    sa.Column('retention_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='First-year retention rate (percentage)'),
    sa.Column('graduation_rate_4_year', sa.Numeric(precision=5, scale=2), nullable=True, comment='4-year graduation rate (percentage)'),
    sa.Column('graduation_rate_6_year', sa.Numeric(precision=5, scale=2), nullable=True, comment='6-year graduation rate (percentage)'),
    sa.Column('graduation_rate_8_year', sa.Numeric(precision=5, scale=2), nullable=True, comment='8-year graduation rate (percentage)'),
    sa.Column('cohort_size', sa.Integer(), nullable=True, comment='Size of the entering cohort'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['ipeds_id'], ['institutions.ipeds_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Graduation and retention rates by cohort year'
    )
    op.create_index(op.f('ix_graduation_data_cohort_year'), 'graduation_data', ['cohort_year'], unique=False)
    op.create_index(op.f('ix_graduation_data_graduation_rate_6_year'), 'graduation_data', ['graduation_rate_6_year'], unique=False)
    op.create_index(op.f('ix_graduation_data_id'), 'graduation_data', ['id'], unique=False)
    op.create_index(op.f('ix_graduation_data_ipeds_id'), 'graduation_data', ['ipeds_id'], unique=False)
    op.create_index(op.f('ix_graduation_data_retention_rate'), 'graduation_data', ['retention_rate'], unique=False)
    op.add_column('institutions', sa.Column('student_faculty_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='Student to faculty ratio (e.g., 17.00 for 17:1)'))
    op.add_column('institutions', sa.Column('size_category', sa.String(length=50), nullable=True, comment='Institution size: Small (<2k), Medium (2k-10k), Large (10k-20k), Very Large (20k+)'))
    op.add_column('institutions', sa.Column('locale', sa.String(length=50), nullable=True, comment='Urbanization level: City, Suburban, Town, Rural'))
    op.create_index(op.f('ix_institutions_size_category'), 'institutions', ['size_category'], unique=False)
    op.create_index(op.f('ix_institutions_student_faculty_ratio'), 'institutions', ['student_faculty_ratio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutions_student_faculty_ratio'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_size_category'), table_name='institutions')
    op.drop_column('institutions', 'locale')
    op.drop_column('institutions', 'size_category')
    op.drop_column('institutions', 'student_faculty_ratio')
    op.drop_index(op.f('ix_graduation_data_retention_rate'), table_name='graduation_data')
    op.drop_index(op.f('ix_graduation_data_ipeds_id'), table_name='graduation_data')
    op.drop_index(op.f('ix_graduation_data_id'), table_name='graduation_data')
    op.drop_index(op.f('ix_graduation_data_graduation_rate_6_year'), table_name='graduation_data')
    op.drop_index(op.f('ix_graduation_data_cohort_year'), table_name='graduation_data')
    op.drop_table('graduation_data')
    op.drop_index(op.f('ix_enrollment_data_total_enrollment'), table_name='enrollment_data')
    op.drop_index(op.f('ix_enrollment_data_ipeds_id'), table_name='enrollment_data')
    op.drop_index(op.f('ix_enrollment_data_id'), table_name='enrollment_data')
    op.drop_index(op.f('ix_enrollment_data_academic_year'), table_name='enrollment_data')
    op.drop_table('enrollment_data')
    op.drop_index(op.f('ix_admissions_data_sat_math_50th'), table_name='admissions_data')
    op.drop_index(op.f('ix_admissions_data_ipeds_id'), table_name='admissions_data')
    op.drop_index(op.f('ix_admissions_data_id'), table_name='admissions_data')
    op.drop_index(op.f('ix_admissions_data_act_composite_50th'), table_name='admissions_data')
    op.drop_index(op.f('ix_admissions_data_acceptance_rate'), table_name='admissions_data')
    op.drop_index(op.f('ix_admissions_data_academic_year'), table_name='admissions_data')
    op.drop_table('admissions_data')
    # ### end Alembic commands ###
