"""add_scholarship_image_fields

Revision ID: 4622ae60e202
Revises: 78edf3e7a6d6
Create Date: 2025-09-13 08:36:54.181969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4622ae60e202'
down_revision: Union[str, None] = '78edf3e7a6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarships', sa.Column('primary_image_url', sa.String(length=500), nullable=True, comment='CDN URL to standardized scholarship card image'))
    op.add_column('scholarships', sa.Column('primary_image_quality_score', sa.Integer(), nullable=True, comment='Quality score 0-100 for ranking scholarships by image quality'))
    op.add_column('scholarships', sa.Column('logo_image_url', sa.String(length=500), nullable=True, comment='CDN URL to organization logo'))
    op.add_column('scholarships', sa.Column('image_extraction_status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'NEEDS_REVIEW', 'FALLBACK_APPLIED', name='imageextractionstatus'), nullable=True, comment='Status of image extraction process'))
    op.add_column('scholarships', sa.Column('image_extraction_date', sa.DateTime(timezone=True), nullable=True, comment='When images were last extracted/updated'))
    op.create_index(op.f('ix_scholarships_image_extraction_status'), 'scholarships', ['image_extraction_status'], unique=False)
    op.create_index(op.f('ix_scholarships_primary_image_quality_score'), 'scholarships', ['primary_image_quality_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholarships_primary_image_quality_score'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_image_extraction_status'), table_name='scholarships')
    op.drop_column('scholarships', 'image_extraction_date')
    op.drop_column('scholarships', 'image_extraction_status')
    op.drop_column('scholarships', 'logo_image_url')
    op.drop_column('scholarships', 'primary_image_quality_score')
    op.drop_column('scholarships', 'primary_image_url')
    # ### end Alembic commands ###
