"""remove boolean flags from scholarships

Revision ID: 5004fa491e95
Revises: 3682fd1f1bbd
Create Date: 2025-10-09 05:17:11.748454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5004fa491e95'
down_revision: Union[str, None] = '3682fd1f1bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarships', 'international_students_eligible')
    op.drop_column('scholarships', 'leadership_essay_required')
    op.drop_column('scholarships', 'work_experience_required')
    op.drop_column('scholarships', 'portfolio_required')
    op.drop_column('scholarships', 'personal_statement_required')
    op.drop_column('scholarships', 'military_affiliation_required')
    op.drop_column('scholarships', 'essay_required')
    op.drop_column('scholarships', 'is_rolling_deadline')
    op.drop_column('scholarships', 'leadership_required')
    op.drop_column('scholarships', 'transcript_required')
    op.drop_column('scholarships', 'interview_required')
    op.drop_column('scholarships', 'need_based_required')
    op.drop_column('scholarships', 'community_service_essay_required')
    op.drop_column('scholarships', 'recommendation_letters_required')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarships', sa.Column('recommendation_letters_required', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('community_service_essay_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('need_based_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('interview_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('transcript_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('leadership_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('is_rolling_deadline', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('essay_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('military_affiliation_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('personal_statement_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('portfolio_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('work_experience_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('leadership_essay_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scholarships', sa.Column('international_students_eligible', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
