"""created institution modelv2

Revision ID: 53bfefcea5aa
Revises: e1210baabccb
Create Date: 2025-09-06 19:43:53.658724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53bfefcea5aa'
down_revision: Union[str, None] = 'e1210baabccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipeds_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('region', sa.Enum('NEW_ENGLAND', 'MID_ATLANTIC', 'EAST_NORTH_CENTRAL', 'WEST_NORTH_CENTRAL', 'SOUTH_ATLANTIC', 'EAST_SOUTH_CENTRAL', 'WEST_SOUTH_CENTRAL', 'MOUNTAIN', 'PACIFIC', name='usregion'), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.Float(), nullable=True),
    sa.Column('president_name', sa.String(length=255), nullable=True),
    sa.Column('president_title', sa.String(length=100), nullable=True),
    sa.Column('control_type', sa.Enum('PUBLIC', 'PRIVATE_NONPROFIT', 'PRIVATE_FOR_PROFIT', name='controltype'), nullable=False),
    sa.Column('size_category', sa.Enum('VERY_SMALL', 'SMALL', 'MEDIUM', 'LARGE', 'VERY_LARGE', name='sizecategory'), nullable=True),
    sa.Column('carnegie_basic', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_carnegie_basic'), 'institutions', ['carnegie_basic'], unique=False)
    op.create_index(op.f('ix_institutions_city'), 'institutions', ['city'], unique=False)
    op.create_index(op.f('ix_institutions_control_type'), 'institutions', ['control_type'], unique=False)
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_ipeds_id'), 'institutions', ['ipeds_id'], unique=True)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_region'), 'institutions', ['region'], unique=False)
    op.create_index(op.f('ix_institutions_size_category'), 'institutions', ['size_category'], unique=False)
    op.create_index(op.f('ix_institutions_state'), 'institutions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutions_state'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_size_category'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_region'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_ipeds_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_control_type'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_city'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_carnegie_basic'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
