"""magicscholar_initial_with_shared_tables

Revision ID: 56b5460a7805
Revises: 
Create Date: 2025-11-22 08:27:00.251936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56b5460a7805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admissions_data', 'institution_id',
               existing_type=sa.INTEGER(),
               comment='Direct foreign key to institutions.id',
               existing_nullable=False)
    op.alter_column('admissions_data', 'ipeds_id',
               existing_type=sa.INTEGER(),
               comment='IPEDS institution identifier',
               existing_nullable=False)
    op.alter_column('admissions_data', 'academic_year',
               existing_type=sa.VARCHAR(length=10),
               comment='Academic year (e.g., 2023-24)',
               existing_nullable=False)
    op.alter_column('admissions_data', 'applications_total',
               existing_type=sa.INTEGER(),
               comment='Total applications received',
               existing_nullable=True)
    op.alter_column('admissions_data', 'admissions_total',
               existing_type=sa.INTEGER(),
               comment='Total students admitted',
               existing_nullable=True)
    op.alter_column('admissions_data', 'enrolled_total',
               existing_type=sa.INTEGER(),
               comment='Total students enrolled',
               existing_nullable=True)
    op.alter_column('admissions_data', 'acceptance_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Acceptance rate as percentage (0-100)',
               existing_nullable=True)
    op.alter_column('admissions_data', 'yield_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Yield rate as percentage (0-100)',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_reading_25th',
               existing_type=sa.INTEGER(),
               comment='SAT Evidence-Based Reading/Writing 25th percentile',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_reading_50th',
               existing_type=sa.INTEGER(),
               comment='SAT Evidence-Based Reading/Writing 50th percentile (median)',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_reading_75th',
               existing_type=sa.INTEGER(),
               comment='SAT Evidence-Based Reading/Writing 75th percentile',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_math_25th',
               existing_type=sa.INTEGER(),
               comment='SAT Math 25th percentile',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_math_50th',
               existing_type=sa.INTEGER(),
               comment='SAT Math 50th percentile (median)',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_math_75th',
               existing_type=sa.INTEGER(),
               comment='SAT Math 75th percentile',
               existing_nullable=True)
    op.alter_column('admissions_data', 'percent_submitting_sat',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Percentage of enrolled students who submitted SAT',
               existing_nullable=True)
    op.alter_column('admissions_data', 'is_admin_verified',
               existing_type=sa.BOOLEAN(),
               comment='True if admin has verified/updated this data via CampusConnect',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('admissions_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('admissions_data_unique', 'admissions_data', type_='unique')
    op.create_table_comment(
        'admissions_data',
        'Admissions statistics and test scores by academic year',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_deadline', 'college_applications', ['deadline'], unique=False)
    op.create_index('idx_user_college_status', 'college_applications', ['user_id', 'status'], unique=False)
    op.create_index('idx_user_institution', 'college_applications', ['user_id', 'institution_id'], unique=True)
    op.create_index(op.f('ix_college_applications_deadline'), 'college_applications', ['deadline'], unique=False)
    op.create_index(op.f('ix_college_applications_id'), 'college_applications', ['id'], unique=False)
    op.create_index(op.f('ix_college_applications_status'), 'college_applications', ['status'], unique=False)
    op.create_foreign_key(None, 'college_applications', 'institutions', ['institution_id'], ['id'])
    op.create_foreign_key(None, 'college_applications', 'users', ['user_id'], ['id'])
    op.drop_index('idx_entity_images_display_order', table_name='entity_images')
    op.drop_index('idx_entity_images_entity', table_name='entity_images')
    op.drop_index('idx_entity_images_featured', table_name='entity_images')
    op.drop_index('idx_entity_images_one_featured', table_name='entity_images', postgresql_where='(is_featured = true)')
    op.alter_column('institutions', 'student_faculty_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Student to faculty ratio (e.g., 17.00 for 17:1)',
               existing_nullable=True)
    op.alter_column('institutions', 'size_category',
               existing_type=sa.VARCHAR(length=50),
               comment='Institution size: Small (<2k), Medium (2k-10k), Large (10k-20k), Very Large (20k+)',
               existing_nullable=True)
    op.alter_column('institutions', 'locale',
               existing_type=sa.VARCHAR(length=50),
               comment='Urbanization level: City, Suburban, Town, Rural',
               existing_nullable=True)
    op.create_index('idx_user_scholarship', 'scholarship_applications', ['user_id', 'scholarship_id'], unique=True)
    op.create_index('idx_user_status', 'scholarship_applications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_scholarship_applications_id'), 'scholarship_applications', ['id'], unique=False)
    op.create_index(op.f('ix_scholarship_applications_status'), 'scholarship_applications', ['status'], unique=False)
    op.create_foreign_key(None, 'scholarship_applications', 'scholarships', ['scholarship_id'], ['id'])
    op.create_foreign_key(None, 'scholarship_applications', 'users', ['user_id'], ['id'])
    op.alter_column('tuition_data', 'id',
               existing_type=sa.INTEGER(),
               comment='Primary key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tuition_data', 'institution_id',
               existing_type=sa.INTEGER(),
               comment='Direct foreign key to institutions.id',
               existing_nullable=False)
    op.alter_column('tuition_data', 'ipeds_id',
               existing_type=sa.INTEGER(),
               comment='Institution IPEDS ID (foreign key)',
               existing_nullable=False)
    op.alter_column('tuition_data', 'academic_year',
               existing_type=sa.VARCHAR(length=10),
               comment='Academic year (e.g., "2025-26")',
               existing_nullable=False)
    op.alter_column('tuition_data', 'data_source',
               existing_type=sa.VARCHAR(length=500),
               comment='Source of the data (e.g., "https://...")',
               existing_nullable=False)
    op.alter_column('tuition_data', 'tuition_in_state',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='In-state tuition cost',
               existing_nullable=True)
    op.alter_column('tuition_data', 'tuition_out_state',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Out-of-state tuition cost',
               existing_nullable=True)
    op.alter_column('tuition_data', 'required_fees_in_state',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Required fees for in-state students',
               existing_nullable=True)
    op.alter_column('tuition_data', 'required_fees_out_state',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Required fees for out-of-state students',
               existing_nullable=True)
    op.alter_column('tuition_data', 'room_board_on_campus',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Room and board costs on campus',
               existing_nullable=True)
    op.alter_column('tuition_data', 'is_admin_verified',
               existing_type=sa.BOOLEAN(),
               comment='True if admin has verified/updated this data via CampusConnect',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tuition_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tuition_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'tuition_data',
        'Tuition and financial data for institutions',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'tuition_data',
        existing_comment='Tuition and financial data for institutions',
        schema=None
    )
    op.alter_column('tuition_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tuition_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tuition_data', 'is_admin_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True if admin has verified/updated this data via CampusConnect',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tuition_data', 'room_board_on_campus',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Room and board costs on campus',
               existing_nullable=True)
    op.alter_column('tuition_data', 'required_fees_out_state',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Required fees for out-of-state students',
               existing_nullable=True)
    op.alter_column('tuition_data', 'required_fees_in_state',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Required fees for in-state students',
               existing_nullable=True)
    op.alter_column('tuition_data', 'tuition_out_state',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Out-of-state tuition cost',
               existing_nullable=True)
    op.alter_column('tuition_data', 'tuition_in_state',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='In-state tuition cost',
               existing_nullable=True)
    op.alter_column('tuition_data', 'data_source',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Source of the data (e.g., "https://...")',
               existing_nullable=False)
    op.alter_column('tuition_data', 'academic_year',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Academic year (e.g., "2025-26")',
               existing_nullable=False)
    op.alter_column('tuition_data', 'ipeds_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Institution IPEDS ID (foreign key)',
               existing_nullable=False)
    op.alter_column('tuition_data', 'institution_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Direct foreign key to institutions.id',
               existing_nullable=False)
    op.alter_column('tuition_data', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'scholarship_applications', type_='foreignkey')
    op.drop_constraint(None, 'scholarship_applications', type_='foreignkey')
    op.drop_index(op.f('ix_scholarship_applications_status'), table_name='scholarship_applications')
    op.drop_index(op.f('ix_scholarship_applications_id'), table_name='scholarship_applications')
    op.drop_index('idx_user_status', table_name='scholarship_applications')
    op.drop_index('idx_user_scholarship', table_name='scholarship_applications')
    op.alter_column('institutions', 'locale',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Urbanization level: City, Suburban, Town, Rural',
               existing_nullable=True)
    op.alter_column('institutions', 'size_category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Institution size: Small (<2k), Medium (2k-10k), Large (10k-20k), Very Large (20k+)',
               existing_nullable=True)
    op.alter_column('institutions', 'student_faculty_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Student to faculty ratio (e.g., 17.00 for 17:1)',
               existing_nullable=True)
    op.create_index('idx_entity_images_one_featured', 'entity_images', ['entity_type', 'entity_id'], unique=False, postgresql_where='(is_featured = true)')
    op.create_index('idx_entity_images_featured', 'entity_images', ['is_featured'], unique=False)
    op.create_index('idx_entity_images_entity', 'entity_images', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_entity_images_display_order', 'entity_images', ['display_order'], unique=False)
    op.drop_constraint(None, 'college_applications', type_='foreignkey')
    op.drop_constraint(None, 'college_applications', type_='foreignkey')
    op.drop_index(op.f('ix_college_applications_status'), table_name='college_applications')
    op.drop_index(op.f('ix_college_applications_id'), table_name='college_applications')
    op.drop_index(op.f('ix_college_applications_deadline'), table_name='college_applications')
    op.drop_index('idx_user_institution', table_name='college_applications')
    op.drop_index('idx_user_college_status', table_name='college_applications')
    op.drop_index('idx_deadline', table_name='college_applications')
    op.drop_table_comment(
        'admissions_data',
        existing_comment='Admissions statistics and test scores by academic year',
        schema=None
    )
    op.create_unique_constraint('admissions_data_unique', 'admissions_data', ['ipeds_id', 'academic_year'])
    op.alter_column('admissions_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('admissions_data', 'is_admin_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True if admin has verified/updated this data via CampusConnect',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('admissions_data', 'percent_submitting_sat',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Percentage of enrolled students who submitted SAT',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_math_75th',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='SAT Math 75th percentile',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_math_50th',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='SAT Math 50th percentile (median)',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_math_25th',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='SAT Math 25th percentile',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_reading_75th',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='SAT Evidence-Based Reading/Writing 75th percentile',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_reading_50th',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='SAT Evidence-Based Reading/Writing 50th percentile (median)',
               existing_nullable=True)
    op.alter_column('admissions_data', 'sat_reading_25th',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='SAT Evidence-Based Reading/Writing 25th percentile',
               existing_nullable=True)
    op.alter_column('admissions_data', 'yield_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Yield rate as percentage (0-100)',
               existing_nullable=True)
    op.alter_column('admissions_data', 'acceptance_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Acceptance rate as percentage (0-100)',
               existing_nullable=True)
    op.alter_column('admissions_data', 'enrolled_total',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total students enrolled',
               existing_nullable=True)
    op.alter_column('admissions_data', 'admissions_total',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total students admitted',
               existing_nullable=True)
    op.alter_column('admissions_data', 'applications_total',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total applications received',
               existing_nullable=True)
    op.alter_column('admissions_data', 'academic_year',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Academic year (e.g., 2023-24)',
               existing_nullable=False)
    op.alter_column('admissions_data', 'ipeds_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='IPEDS institution identifier',
               existing_nullable=False)
    op.alter_column('admissions_data', 'institution_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Direct foreign key to institutions.id',
               existing_nullable=False)
    # ### end Alembic commands ###
