"""adding settings to profile model for confetti control

Revision ID: 57895a2df522
Revises: b9f3eb77c8b1
Create Date: 2025-11-13 03:33:17.530979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57895a2df522'
down_revision: Union[str, None] = 'b9f3eb77c8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{"confetti_enabled": true}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'settings')
    # ### end Alembic commands ###
