"""increase character limit for datasource for tuition

Revision ID: 71dcfe83431f
Revises: f3442b4564a5
Create Date: 2025-10-14 04:49:44.697736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71dcfe83431f'
down_revision: Union[str, None] = 'f3442b4564a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tuition_data', 'data_source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               comment='Source of the data (e.g., "IPEDS", "Manual", "School Website)',
               existing_comment='Source of the data (e.g., "IPEDS", "Manual")',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tuition_data', 'data_source',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               comment='Source of the data (e.g., "IPEDS", "Manual")',
               existing_comment='Source of the data (e.g., "IPEDS", "Manual", "School Website)',
               existing_nullable=False)
    # ### end Alembic commands ###
