"""Add ipeds_id foreign key to s2023_is

Revision ID: 78edf3e7a6d6
Revises: a4cdd30995a3
Create Date: 2025-09-11 12:00:28.613247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78edf3e7a6d6'
down_revision: Union[str, None] = 'a4cdd30995a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('step2_ic2023_ay', 'tuition_in_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='In-state tuition',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'tuition_out_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Out-of-state tuition',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'required_fees',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Required fees',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'tuition_fees_in_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='In-state tuition + fees',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'tuition_fees_out_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Out-of-state tuition + fees',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'room_board_on_campus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='On-campus room and board',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'room_board_off_campus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Off-campus room and board',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'books_supplies',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Books and supplies cost',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'personal_expenses',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Personal expenses',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'transportation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Transportation costs',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'has_tuition_data',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Has any tuition data',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'has_fees_data',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Has fees data',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'data_completeness_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0-100 score of data completeness',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'validation_issues',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Any data validation issues',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'validation_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, valid, issues',
               existing_nullable=True)
    op.drop_index('idx_step2_academic_year', table_name='step2_ic2023_ay')
    op.drop_index('idx_step2_ipeds_id', table_name='step2_ic2023_ay')
    op.drop_index('idx_step2_tuition_in_state', table_name='step2_ic2023_ay')
    op.drop_index('idx_step2_tuition_out_state', table_name='step2_ic2023_ay')
    op.drop_index('idx_step2_validation_status', table_name='step2_ic2023_ay')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_step2_validation_status', 'step2_ic2023_ay', ['validation_status'], unique=False)
    op.create_index('idx_step2_tuition_out_state', 'step2_ic2023_ay', ['tuition_out_state'], unique=False)
    op.create_index('idx_step2_tuition_in_state', 'step2_ic2023_ay', ['tuition_in_state'], unique=False)
    op.create_index('idx_step2_ipeds_id', 'step2_ic2023_ay', ['ipeds_id'], unique=False)
    op.create_index('idx_step2_academic_year', 'step2_ic2023_ay', ['academic_year'], unique=False)
    op.alter_column('step2_ic2023_ay', 'validation_status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, valid, issues',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'validation_issues',
               existing_type=sa.TEXT(),
               comment='Any data validation issues',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'data_completeness_score',
               existing_type=sa.INTEGER(),
               comment='0-100 score of data completeness',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'has_fees_data',
               existing_type=sa.BOOLEAN(),
               comment='Has fees data',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'has_tuition_data',
               existing_type=sa.BOOLEAN(),
               comment='Has any tuition data',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'transportation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Transportation costs',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'personal_expenses',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Personal expenses',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'books_supplies',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Books and supplies cost',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'room_board_off_campus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Off-campus room and board',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'room_board_on_campus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='On-campus room and board',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'tuition_fees_out_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Out-of-state tuition + fees',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'tuition_fees_in_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='In-state tuition + fees',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'required_fees',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Required fees',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'tuition_out_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Out-of-state tuition',
               existing_nullable=True)
    op.alter_column('step2_ic2023_ay', 'tuition_in_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='In-state tuition',
               existing_nullable=True)
    # ### end Alembic commands ###
