"""step2_financial data

Revision ID: a4cdd30995a3
Revises: 3e6eeba8f764
Create Date: 2025-09-11 11:45:04.057003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4cdd30995a3'
down_revision: Union[str, None] = '3e6eeba8f764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step2_ic2023_ay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipeds_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('tuition_in_state', sa.Float(), nullable=True, comment='In-state tuition'),
    sa.Column('tuition_out_state', sa.Float(), nullable=True, comment='Out-of-state tuition'),
    sa.Column('required_fees', sa.Float(), nullable=True, comment='Required fees'),
    sa.Column('tuition_fees_in_state', sa.Float(), nullable=True, comment='In-state tuition + fees'),
    sa.Column('tuition_fees_out_state', sa.Float(), nullable=True, comment='Out-of-state tuition + fees'),
    sa.Column('room_board_on_campus', sa.Float(), nullable=True, comment='On-campus room and board'),
    sa.Column('room_board_off_campus', sa.Float(), nullable=True, comment='Off-campus room and board'),
    sa.Column('books_supplies', sa.Float(), nullable=True, comment='Books and supplies cost'),
    sa.Column('personal_expenses', sa.Float(), nullable=True, comment='Personal expenses'),
    sa.Column('transportation', sa.Float(), nullable=True, comment='Transportation costs'),
    sa.Column('has_tuition_data', sa.Boolean(), nullable=True, comment='Has any tuition data'),
    sa.Column('has_fees_data', sa.Boolean(), nullable=True, comment='Has fees data'),
    sa.Column('data_completeness_score', sa.Integer(), nullable=True, comment='0-100 score of data completeness'),
    sa.Column('validation_issues', sa.Text(), nullable=True, comment='Any data validation issues'),
    sa.Column('validation_status', sa.String(length=20), nullable=True, comment='pending, valid, issues'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ipeds_id'], ['institutions.ipeds_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_step2_academic_year', 'step2_ic2023_ay', ['academic_year'], unique=False)
    op.create_index('idx_step2_ipeds_id', 'step2_ic2023_ay', ['ipeds_id'], unique=False)
    op.create_index('idx_step2_tuition_in_state', 'step2_ic2023_ay', ['tuition_in_state'], unique=False)
    op.create_index('idx_step2_tuition_out_state', 'step2_ic2023_ay', ['tuition_out_state'], unique=False)
    op.create_index('idx_step2_validation_status', 'step2_ic2023_ay', ['validation_status'], unique=False)
    op.create_index(op.f('ix_step2_ic2023_ay_id'), 'step2_ic2023_ay', ['id'], unique=False)
    op.create_index(op.f('ix_step2_ic2023_ay_ipeds_id'), 'step2_ic2023_ay', ['ipeds_id'], unique=False)
    op.add_column('institutions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('institutions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_institution_control_size', 'institutions', ['control_type', 'size_category'], unique=False)
    op.create_index('idx_institution_customer_rank', 'institutions', ['customer_rank'], unique=False)
    op.create_index('idx_institution_image_quality', 'institutions', ['primary_image_quality_score'], unique=False)
    op.create_index('idx_institution_name', 'institutions', ['name'], unique=False)
    op.create_index('idx_institution_state_city', 'institutions', ['state', 'city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_institution_state_city', table_name='institutions')
    op.drop_index('idx_institution_name', table_name='institutions')
    op.drop_index('idx_institution_image_quality', table_name='institutions')
    op.drop_index('idx_institution_customer_rank', table_name='institutions')
    op.drop_index('idx_institution_control_size', table_name='institutions')
    op.drop_column('institutions', 'updated_at')
    op.drop_column('institutions', 'created_at')
    op.drop_index(op.f('ix_step2_ic2023_ay_ipeds_id'), table_name='step2_ic2023_ay')
    op.drop_index(op.f('ix_step2_ic2023_ay_id'), table_name='step2_ic2023_ay')
    op.drop_index('idx_step2_validation_status', table_name='step2_ic2023_ay')
    op.drop_index('idx_step2_tuition_out_state', table_name='step2_ic2023_ay')
    op.drop_index('idx_step2_tuition_in_state', table_name='step2_ic2023_ay')
    op.drop_index('idx_step2_ipeds_id', table_name='step2_ic2023_ay')
    op.drop_index('idx_step2_academic_year', table_name='step2_ic2023_ay')
    op.drop_table('step2_ic2023_ay')
    # ### end Alembic commands ###
