"""create location preference to user  profile

Revision ID: a7fada48936e
Revises: dbf242a08a02
Create Date: 2025-10-16 05:22:44.375123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fada48936e'
down_revision: Union[str, None] = 'dbf242a08a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('location_preference', sa.String(length=2), nullable=True))
    op.create_index(op.f('ix_user_profiles_location_preference'), 'user_profiles', ['location_preference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_location_preference'), table_name='user_profiles')
    op.drop_column('user_profiles', 'location_preference')
    # ### end Alembic commands ###
