"""Initial schema with profiles and essays

Revision ID: af487effa627
Revises: 
Create Date: 2025-08-29 12:13:23.724871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af487effa627'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_states_id'), 'oauth_states', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_accounts_id'), 'oauth_accounts', ['id'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('scholarship_type', sa.Enum('ACADEMIC_MERIT', 'NEED_BASED', 'ATHLETIC', 'STEM', 'ARTS', 'DIVERSITY', 'FIRST_GENERATION', 'COMMUNITY_SERVICE', 'LEADERSHIP', 'LOCAL_COMMUNITY', 'EMPLOYER_SPONSORED', 'MILITARY', 'RELIGIOUS', 'CAREER_SPECIFIC', 'ESSAY_BASED', 'RENEWABLE', name='scholarshiptype'), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'DRAFT', 'PENDING_REVIEW', name='scholarshipstatus'), nullable=False),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MODERATE', 'HARD', 'VERY_HARD', name='difficultylevel'), nullable=False),
    sa.Column('amount_min', sa.Integer(), nullable=True),
    sa.Column('amount_max', sa.Integer(), nullable=True),
    sa.Column('amount_exact', sa.Integer(), nullable=True),
    sa.Column('is_renewable', sa.Boolean(), nullable=True),
    sa.Column('renewal_years', sa.Integer(), nullable=True),
    sa.Column('number_of_awards', sa.Integer(), nullable=True),
    sa.Column('min_gpa', sa.Float(), nullable=True),
    sa.Column('max_gpa', sa.Float(), nullable=True),
    sa.Column('min_sat_score', sa.Integer(), nullable=True),
    sa.Column('min_act_score', sa.Integer(), nullable=True),
    sa.Column('required_majors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('excluded_majors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('academic_level', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('eligible_ethnicities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('gender_requirements', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('first_generation_college_required', sa.Boolean(), nullable=True),
    sa.Column('income_max', sa.Integer(), nullable=True),
    sa.Column('income_min', sa.Integer(), nullable=True),
    sa.Column('need_based_required', sa.Boolean(), nullable=True),
    sa.Column('eligible_states', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('eligible_cities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('eligible_counties', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('zip_codes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('international_students_eligible', sa.Boolean(), nullable=True),
    sa.Column('eligible_schools', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('high_school_names', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('graduation_year_min', sa.Integer(), nullable=True),
    sa.Column('graduation_year_max', sa.Integer(), nullable=True),
    sa.Column('required_activities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('volunteer_hours_min', sa.Integer(), nullable=True),
    sa.Column('leadership_required', sa.Boolean(), nullable=True),
    sa.Column('work_experience_required', sa.Boolean(), nullable=True),
    sa.Column('special_talents', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('essay_required', sa.Boolean(), nullable=True),
    sa.Column('essay_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('essay_word_limit', sa.Integer(), nullable=True),
    sa.Column('transcript_required', sa.Boolean(), nullable=True),
    sa.Column('recommendation_letters_required', sa.Integer(), nullable=True),
    sa.Column('portfolio_required', sa.Boolean(), nullable=True),
    sa.Column('interview_required', sa.Boolean(), nullable=True),
    sa.Column('personal_statement_required', sa.Boolean(), nullable=True),
    sa.Column('leadership_essay_required', sa.Boolean(), nullable=True),
    sa.Column('community_service_essay_required', sa.Boolean(), nullable=True),
    sa.Column('application_opens', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('award_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_rolling_deadline', sa.Boolean(), nullable=True),
    sa.Column('languages_preferred', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('military_affiliation_required', sa.Boolean(), nullable=True),
    sa.Column('employer_affiliation', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('applications_count', sa.Integer(), nullable=True),
    sa.Column('ai_generated_summary', sa.Text(), nullable=True),
    sa.Column('matching_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_index(op.f('ix_scholarships_organization'), 'scholarships', ['organization'], unique=False)
    op.create_index(op.f('ix_scholarships_scholarship_type'), 'scholarships', ['scholarship_type'], unique=False)
    op.create_index(op.f('ix_scholarships_title'), 'scholarships', ['title'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('high_school_name', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('sat_score', sa.Integer(), nullable=True),
    sa.Column('act_score', sa.Integer(), nullable=True),
    sa.Column('intended_major', sa.String(length=255), nullable=True),
    sa.Column('academic_interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('career_goals', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('extracurricular_activities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('volunteer_experience', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('volunteer_hours', sa.Integer(), nullable=True),
    sa.Column('work_experience', sa.JSON(), nullable=True),
    sa.Column('ethnicity', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('first_generation_college', sa.Boolean(), nullable=True),
    sa.Column('household_income_range', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('preferred_college_size', sa.String(length=50), nullable=True),
    sa.Column('preferred_college_location', sa.String(length=100), nullable=True),
    sa.Column('college_application_status', sa.String(length=50), nullable=True),
    sa.Column('has_personal_statement', sa.Boolean(), nullable=True),
    sa.Column('has_leadership_essay', sa.Boolean(), nullable=True),
    sa.Column('has_challenges_essay', sa.Boolean(), nullable=True),
    sa.Column('has_diversity_essay', sa.Boolean(), nullable=True),
    sa.Column('scholarship_types_interested', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('application_deadline_preference', sa.String(length=50), nullable=True),
    sa.Column('languages_spoken', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('special_talents', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('additional_notes', sa.String(length=500), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('scholarship_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reasons', sa.JSON(), nullable=True),
    sa.Column('mismatch_reasons', sa.JSON(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('interested', sa.Boolean(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('bookmarked', sa.Boolean(), nullable=True),
    sa.Column('application_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('match_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_matches_id'), 'scholarship_matches', ['id'], unique=False)
    op.create_index(op.f('ix_scholarship_matches_scholarship_id'), 'scholarship_matches', ['scholarship_id'], unique=False)
    op.create_index(op.f('ix_scholarship_matches_user_id'), 'scholarship_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholarship_matches_user_id'), table_name='scholarship_matches')
    op.drop_index(op.f('ix_scholarship_matches_scholarship_id'), table_name='scholarship_matches')
    op.drop_index(op.f('ix_scholarship_matches_id'), table_name='scholarship_matches')
    op.drop_table('scholarship_matches')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_scholarships_title'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_scholarship_type'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_organization'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_oauth_accounts_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_id'), table_name='oauth_states')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###
