"""Initial Migration

Revision ID: b440136139c6
Revises: a7fada48936e
Create Date: 2025-10-31 05:11:04.635626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b440136139c6'
down_revision: Union[str, None] = 'a7fada48936e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('resume_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'resume_url')
    op.drop_column('user_profiles', 'profile_image_url')
    # ### end Alembic commands ###
