"""Create college applications table

Revision ID: b9f3eb77c8b1
Revises: b5bfc9ebcca3
Create Date: 2025-11-07 05:31:34.176912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f3eb77c8b1'
down_revision: Union[str, None] = 'b5bfc9ebcca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RESEARCHING', 'PLANNING', 'IN_PROGRESS', 'SUBMITTED', 'ACCEPTED', 'WAITLISTED', 'REJECTED', 'DECLINED', 'ENROLLED', name='applicationstatus_college'), nullable=False),
    sa.Column('application_type', sa.Enum('EARLY_DECISION', 'EARLY_ACTION', 'REGULAR_DECISION', 'ROLLING', name='applicationtype_college'), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('actual_decision_date', sa.Date(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('application_fee', sa.Integer(), nullable=True),
    sa.Column('fee_waiver_obtained', sa.Boolean(), nullable=False),
    sa.Column('application_portal', sa.Text(), nullable=True),
    sa.Column('portal_url', sa.Text(), nullable=True),
    sa.Column('portal_username', sa.Text(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deadline', 'college_applications', ['deadline'], unique=False)
    op.create_index('idx_user_college_status', 'college_applications', ['user_id', 'status'], unique=False)
    op.create_index('idx_user_institution', 'college_applications', ['user_id', 'institution_id'], unique=True)
    op.create_index(op.f('ix_college_applications_deadline'), 'college_applications', ['deadline'], unique=False)
    op.create_index(op.f('ix_college_applications_id'), 'college_applications', ['id'], unique=False)
    op.create_index(op.f('ix_college_applications_status'), 'college_applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_college_applications_status'), table_name='college_applications')
    op.drop_index(op.f('ix_college_applications_id'), table_name='college_applications')
    op.drop_index(op.f('ix_college_applications_deadline'), table_name='college_applications')
    op.drop_index('idx_user_institution', table_name='college_applications')
    op.drop_index('idx_user_college_status', table_name='college_applications')
    op.drop_index('idx_deadline', table_name='college_applications')
    op.drop_table('college_applications')
    # ### end Alembic commands ###
