"""add scholarship application tracking

Revision ID: be17bf4bc02b
Revises: 3f72486f5876
Create Date: 2025-11-06 04:59:21.706417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be17bf4bc02b'
down_revision: Union[str, None] = '3f72486f5876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INTERESTED', 'PLANNING', 'IN_PROGRESS', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'NOT_PURSUING', name='applicationstatus'), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('essay_draft', sa.Text(), nullable=True),
    sa.Column('documents_needed', sa.Text(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('award_amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_scholarship', 'scholarship_applications', ['user_id', 'scholarship_id'], unique=True)
    op.create_index('idx_user_status', 'scholarship_applications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_scholarship_applications_id'), 'scholarship_applications', ['id'], unique=False)
    op.create_index(op.f('ix_scholarship_applications_status'), 'scholarship_applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholarship_applications_status'), table_name='scholarship_applications')
    op.drop_index(op.f('ix_scholarship_applications_id'), table_name='scholarship_applications')
    op.drop_index('idx_user_status', table_name='scholarship_applications')
    op.drop_index('idx_user_scholarship', table_name='scholarship_applications')
    op.drop_table('scholarship_applications')
    # ### end Alembic commands ###
