"""Adding Customer Rank Column

Revision ID: c2f3910292d7
Revises: 86fd2b11055e
Create Date: 2025-09-09 04:21:13.379875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f3910292d7'
down_revision: Union[str, None] = '86fd2b11055e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('customer_rank', sa.Integer(), nullable=True, comment='Customer ranking for advertising priority (higher = better placement)'))
    op.create_index(op.f('ix_institutions_customer_rank'), 'institutions', ['customer_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutions_customer_rank'), table_name='institutions')
    op.drop_column('institutions', 'customer_rank')
    # ### end Alembic commands ###
