"""created college application tracking functionality

Revision ID: ccde1d6c3a7e
Revises: be17bf4bc02b
Create Date: 2025-11-07 04:48:17.043999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccde1d6c3a7e'
down_revision: Union[str, None] = 'be17bf4bc02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
