"""simplifying tuition data again

Revision ID: dbf242a08a02
Revises: 71dcfe83431f
Create Date: 2025-10-14 09:46:09.850044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbf242a08a02'
down_revision: Union[str, None] = '71dcfe83431f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tuition_data', 'academic_year',
               existing_type=sa.VARCHAR(length=10),
               comment='Academic year (e.g., "2025-26")',
               existing_comment='Academic year (e.g., "2023-24")',
               existing_nullable=False)
    op.alter_column('tuition_data', 'data_source',
               existing_type=sa.VARCHAR(length=500),
               comment='Source of the data (e.g., "https://...")',
               existing_comment='Source of the data (e.g., "IPEDS", "Manual", "School Website)',
               existing_nullable=False)
    op.drop_index('ix_tuition_data_data_completeness_score', table_name='tuition_data')
    op.drop_index('ix_tuition_data_has_fees_data', table_name='tuition_data')
    op.drop_index('ix_tuition_data_has_living_data', table_name='tuition_data')
    op.drop_index('ix_tuition_data_has_tuition_data', table_name='tuition_data')
    op.drop_index('ix_tuition_data_tuition_fees_in_state', table_name='tuition_data')
    op.drop_index('ix_tuition_data_tuition_fees_out_state', table_name='tuition_data')
    op.drop_index('ix_tuition_data_validation_status', table_name='tuition_data')
    op.drop_column('tuition_data', 'data_completeness_score')
    op.drop_column('tuition_data', 'has_tuition_data')
    op.drop_column('tuition_data', 'tuition_fees_in_state')
    op.drop_column('tuition_data', 'validation_status')
    op.drop_column('tuition_data', 'has_living_data')
    op.drop_column('tuition_data', 'has_fees_data')
    op.drop_column('tuition_data', 'tuition_fees_out_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuition_data', sa.Column('tuition_fees_out_state', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Total tuition + fees for out-of-state'))
    op.add_column('tuition_data', sa.Column('has_fees_data', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether fee data is available'))
    op.add_column('tuition_data', sa.Column('has_living_data', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether living expense data is available'))
    op.add_column('tuition_data', sa.Column('validation_status', postgresql.ENUM('PENDING', 'VALIDATED', 'NEEDS_REVIEW', 'FAILED', name='validationstatus'), autoincrement=False, nullable=False, comment='Data validation status'))
    op.add_column('tuition_data', sa.Column('tuition_fees_in_state', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Total tuition + fees for in-state'))
    op.add_column('tuition_data', sa.Column('has_tuition_data', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether tuition data is available'))
    op.add_column('tuition_data', sa.Column('data_completeness_score', sa.INTEGER(), autoincrement=False, nullable=False, comment='Data completeness score (0-100)'))
    op.create_index('ix_tuition_data_validation_status', 'tuition_data', ['validation_status'], unique=False)
    op.create_index('ix_tuition_data_tuition_fees_out_state', 'tuition_data', ['tuition_fees_out_state'], unique=False)
    op.create_index('ix_tuition_data_tuition_fees_in_state', 'tuition_data', ['tuition_fees_in_state'], unique=False)
    op.create_index('ix_tuition_data_has_tuition_data', 'tuition_data', ['has_tuition_data'], unique=False)
    op.create_index('ix_tuition_data_has_living_data', 'tuition_data', ['has_living_data'], unique=False)
    op.create_index('ix_tuition_data_has_fees_data', 'tuition_data', ['has_fees_data'], unique=False)
    op.create_index('ix_tuition_data_data_completeness_score', 'tuition_data', ['data_completeness_score'], unique=False)
    op.alter_column('tuition_data', 'data_source',
               existing_type=sa.VARCHAR(length=500),
               comment='Source of the data (e.g., "IPEDS", "Manual", "School Website)',
               existing_comment='Source of the data (e.g., "https://...")',
               existing_nullable=False)
    op.alter_column('tuition_data', 'academic_year',
               existing_type=sa.VARCHAR(length=10),
               comment='Academic year (e.g., "2023-24")',
               existing_comment='Academic year (e.g., "2025-26")',
               existing_nullable=False)
    # ### end Alembic commands ###
