"""add essay boolean flags to user profiles

Revision ID: ddf54ed1ba6e
Revises: 0512db48d27e
Create Date: 2025-08-29 11:59:15.841537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf54ed1ba6e'
down_revision: Union[str, None] = '0512db48d27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
