"""change phone from float to string

Revision ID: e96469e4d170
Revises: f1493e2db8a8
Create Date: 2025-09-07 08:36:37.146331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96469e4d170'
down_revision: Union[str, None] = 'f1493e2db8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institutions', 'phone',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institutions', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
