"""simplified admissions table again

Revision ID: f02e805e59d3
Revises: 353dd1fda711
Create Date: 2025-11-03 13:43:43.571208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02e805e59d3'
down_revision: Union[str, None] = '353dd1fda711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admissions_data', 'percent_submitting_act')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions_data', sa.Column('percent_submitting_act', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='Percentage of enrolled students who submitted ACT'))
    # ### end Alembic commands ###
