"""remove carnegie_basic column

Revision ID: f1493e2db8a8
Revises: 2719ee7def26
Create Date: 2025-09-07 08:13:52.978804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1493e2db8a8'
down_revision: Union[str, None] = '2719ee7def26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_institutions_carnegie_basic', table_name='institutions')
    op.drop_column('institutions', 'carnegie_basic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('carnegie_basic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_institutions_carnegie_basic', 'institutions', ['carnegie_basic'], unique=False)
    # ### end Alembic commands ###
