"""simplified tuition data table

Revision ID: f3442b4564a5
Revises: 2388ad6d2bcb
Create Date: 2025-10-13 21:20:12.234501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3442b4564a5'
down_revision: Union[str, None] = '2388ad6d2bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tuition_data', 'books_supplies')
    op.drop_column('tuition_data', 'room_board_off_campus')
    op.drop_column('tuition_data', 'transportation')
    op.drop_column('tuition_data', 'personal_expenses')
    op.drop_column('tuition_data', 'room_board_breakdown')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuition_data', sa.Column('room_board_breakdown', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON breakdown of room/board costs: {"housing": 9346, "meals": 5358, "total": 14704}'))
    op.add_column('tuition_data', sa.Column('personal_expenses', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Personal/miscellaneous expenses'))
    op.add_column('tuition_data', sa.Column('transportation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Transportation costs'))
    op.add_column('tuition_data', sa.Column('room_board_off_campus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Room and board costs off campus'))
    op.add_column('tuition_data', sa.Column('books_supplies', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Books and supplies cost'))
    # ### end Alembic commands ###
