"""Add s2023_is faculty metrics table

Revision ID: fe3435a26779
Revises: c2f3910292d7
Create Date: 2025-09-10 04:14:24.104290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3435a26779'
down_revision: Union[str, None] = 'c2f3910292d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unitid', sa.String(length=10), nullable=False),
    sa.Column('total_faculty', sa.Integer(), nullable=False),
    sa.Column('female_faculty_percent', sa.Float(), nullable=False),
    sa.Column('male_faculty_percent', sa.Float(), nullable=False),
    sa.Column('diversity_category', sa.String(length=20), nullable=False),
    sa.Column('faculty_size_category', sa.String(length=20), nullable=False),
    sa.Column('faculty_description', sa.Text(), nullable=False),
    sa.Column('diversity_index', sa.Float(), nullable=False),
    sa.Column('asian_faculty_percent', sa.Float(), nullable=False),
    sa.Column('black_faculty_percent', sa.Float(), nullable=False),
    sa.Column('hispanic_faculty_percent', sa.Float(), nullable=False),
    sa.Column('white_faculty_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_metrics_id'), 'faculty_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_metrics_unitid'), 'faculty_metrics', ['unitid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_metrics_unitid'), table_name='faculty_metrics')
    op.drop_index(op.f('ix_faculty_metrics_id'), table_name='faculty_metrics')
    op.drop_table('faculty_metrics')
    # ### end Alembic commands ###
