"""Add user profiles table with privacy controls

Revision ID: 488ec444ba96
Revises: f39ec1bc88ae
Create Date: 2025-08-10 09:04:26.315133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488ec444ba96'
down_revision: Union[str, None] = 'f39ec1bc88ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('profile_photo_filename', sa.String(length=255), nullable=True),
    sa.Column('profile_photo_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('high_school_name', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('class_rank', sa.Integer(), nullable=True),
    sa.Column('class_size', sa.Integer(), nullable=True),
    sa.Column('sat_score', sa.Integer(), nullable=True),
    sa.Column('act_score', sa.Integer(), nullable=True),
    sa.Column('sports_played', sa.JSON(), nullable=True),
    sa.Column('athletic_positions', sa.JSON(), nullable=True),
    sa.Column('years_participated', sa.JSON(), nullable=True),
    sa.Column('team_captain', sa.JSON(), nullable=True),
    sa.Column('athletic_awards', sa.JSON(), nullable=True),
    sa.Column('volunteer_hours', sa.Integer(), nullable=True),
    sa.Column('volunteer_organizations', sa.JSON(), nullable=True),
    sa.Column('leadership_positions', sa.JSON(), nullable=True),
    sa.Column('extracurricular_activities', sa.JSON(), nullable=True),
    sa.Column('work_experience', sa.JSON(), nullable=True),
    sa.Column('honors_courses', sa.JSON(), nullable=True),
    sa.Column('academic_awards', sa.JSON(), nullable=True),
    sa.Column('intended_major', sa.String(length=255), nullable=True),
    sa.Column('college_preferences', sa.JSON(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('personal_statement', sa.Text(), nullable=True),
    sa.Column('career_essay', sa.Text(), nullable=True),
    sa.Column('athletic_impact_essay', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
