"""Add scholarships table

Revision ID: 738f0d6e0faa
Revises: 849ad52c52b0
Create Date: 2025-08-09 07:07:16.512338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738f0d6e0faa'
down_revision: Union[str, None] = '849ad52c52b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('amount_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_exact', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('renewable', sa.Boolean(), nullable=True),
    sa.Column('max_renewals', sa.String(length=50), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('eligibility_criteria', sa.JSON(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('academic_requirements', sa.JSON(), nullable=True),
    sa.Column('demographic_criteria', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('scholarship_type', sa.Enum('MERIT', 'NEED_BASED', 'ATHLETIC', 'MINORITY', 'FIELD_SPECIFIC', 'GEOGRAPHIC', 'FIRST_GENERATION', 'COMMUNITY_SERVICE', 'OTHER', name='scholarshiptype'), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'SUSPENDED', name='scholarshipstatus'), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('application_count', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_external_id'), 'scholarships', ['external_id'], unique=False)
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_index(op.f('ix_scholarships_title'), 'scholarships', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholarships_title'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_external_id'), table_name='scholarships')
    op.drop_table('scholarships')
    # ### end Alembic commands ###
