"""Initial Migration

Revision ID: 49a8810018f5
Revises: 
Create Date: 2025-11-22 05:18:13.019226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49a8810018f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipeds_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('control_type', sa.Enum('PUBLIC', 'PRIVATE_NONPROFIT', 'PRIVATE_FOR_PROFIT', name='controltype'), nullable=False),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('student_faculty_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='Student to faculty ratio (e.g., 17.00 for 17:1)'),
    sa.Column('size_category', sa.String(length=50), nullable=True, comment='Institution size: Small (<2k), Medium (2k-10k), Large (10k-20k), Very Large (20k+)'),
    sa.Column('locale', sa.String(length=50), nullable=True, comment='Urbanization level: City, Suburban, Town, Rural'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_institution_state_city', 'institutions', ['state', 'city'], unique=False)
    op.create_index(op.f('ix_institutions_city'), 'institutions', ['city'], unique=False)
    op.create_index(op.f('ix_institutions_control_type'), 'institutions', ['control_type'], unique=False)
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_ipeds_id'), 'institutions', ['ipeds_id'], unique=True)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_size_category'), 'institutions', ['size_category'], unique=False)
    op.create_index(op.f('ix_institutions_state'), 'institutions', ['state'], unique=False)
    op.create_index(op.f('ix_institutions_student_faculty_ratio'), 'institutions', ['student_faculty_ratio'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_states_id'), 'oauth_states', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=True)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('scholarship_type', sa.Enum('ACADEMIC_MERIT', 'NEED_BASED', 'STEM', 'ARTS', 'DIVERSITY', 'ATHLETIC', 'LEADERSHIP', 'MILITARY', 'CAREER_SPECIFIC', 'OTHER', name='scholarshiptype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'DRAFT', 'PENDING_REVIEW', name='scholarshipstatus'), nullable=False),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MODERATE', 'HARD', 'VERY_HARD', name='difficultylevel'), nullable=False),
    sa.Column('amount_min', sa.Integer(), nullable=False),
    sa.Column('amount_max', sa.Integer(), nullable=False),
    sa.Column('is_renewable', sa.Boolean(), nullable=False),
    sa.Column('number_of_awards', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('application_opens', sa.Date(), nullable=True),
    sa.Column('for_academic_year', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('min_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('applications_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_deadline'), 'scholarships', ['deadline'], unique=False)
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_index(op.f('ix_scholarships_organization'), 'scholarships', ['organization'], unique=False)
    op.create_index(op.f('ix_scholarships_scholarship_type'), 'scholarships', ['scholarship_type'], unique=False)
    op.create_index(op.f('ix_scholarships_title'), 'scholarships', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admissions_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False, comment='Direct foreign key to institutions.id'),
    sa.Column('ipeds_id', sa.Integer(), nullable=False, comment='IPEDS institution identifier'),
    sa.Column('academic_year', sa.String(length=10), nullable=False, comment='Academic year (e.g., 2023-24)'),
    sa.Column('applications_total', sa.Integer(), nullable=True, comment='Total applications received'),
    sa.Column('admissions_total', sa.Integer(), nullable=True, comment='Total students admitted'),
    sa.Column('enrolled_total', sa.Integer(), nullable=True, comment='Total students enrolled'),
    sa.Column('acceptance_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Acceptance rate as percentage (0-100)'),
    sa.Column('yield_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Yield rate as percentage (0-100)'),
    sa.Column('sat_reading_25th', sa.Integer(), nullable=True, comment='SAT Evidence-Based Reading/Writing 25th percentile'),
    sa.Column('sat_reading_50th', sa.Integer(), nullable=True, comment='SAT Evidence-Based Reading/Writing 50th percentile (median)'),
    sa.Column('sat_reading_75th', sa.Integer(), nullable=True, comment='SAT Evidence-Based Reading/Writing 75th percentile'),
    sa.Column('sat_math_25th', sa.Integer(), nullable=True, comment='SAT Math 25th percentile'),
    sa.Column('sat_math_50th', sa.Integer(), nullable=True, comment='SAT Math 50th percentile (median)'),
    sa.Column('sat_math_75th', sa.Integer(), nullable=True, comment='SAT Math 75th percentile'),
    sa.Column('percent_submitting_sat', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage of enrolled students who submitted SAT'),
    sa.Column('is_admin_verified', sa.Boolean(), nullable=False, comment='True if admin has verified/updated this data via CampusConnect'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ipeds_id'], ['institutions.ipeds_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Admissions statistics and test scores by academic year'
    )
    op.create_index(op.f('ix_admissions_data_academic_year'), 'admissions_data', ['academic_year'], unique=False)
    op.create_index(op.f('ix_admissions_data_acceptance_rate'), 'admissions_data', ['acceptance_rate'], unique=False)
    op.create_index(op.f('ix_admissions_data_id'), 'admissions_data', ['id'], unique=False)
    op.create_index(op.f('ix_admissions_data_institution_id'), 'admissions_data', ['institution_id'], unique=False)
    op.create_index(op.f('ix_admissions_data_ipeds_id'), 'admissions_data', ['ipeds_id'], unique=False)
    op.create_index(op.f('ix_admissions_data_sat_math_50th'), 'admissions_data', ['sat_math_50th'], unique=False)
    op.create_table('college_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RESEARCHING', 'PLANNING', 'IN_PROGRESS', 'SUBMITTED', 'ACCEPTED', 'WAITLISTED', 'REJECTED', 'DECLINED', 'ENROLLED', name='applicationstatus_college'), nullable=False),
    sa.Column('application_type', sa.Enum('EARLY_DECISION', 'EARLY_ACTION', 'REGULAR_DECISION', 'ROLLING', name='applicationtype_college'), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('actual_decision_date', sa.Date(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('application_fee', sa.Integer(), nullable=True),
    sa.Column('fee_waiver_obtained', sa.Boolean(), nullable=False),
    sa.Column('application_portal', sa.Text(), nullable=True),
    sa.Column('portal_url', sa.Text(), nullable=True),
    sa.Column('portal_username', sa.Text(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deadline', 'college_applications', ['deadline'], unique=False)
    op.create_index('idx_user_college_status', 'college_applications', ['user_id', 'status'], unique=False)
    op.create_index('idx_user_institution', 'college_applications', ['user_id', 'institution_id'], unique=True)
    op.create_index(op.f('ix_college_applications_deadline'), 'college_applications', ['deadline'], unique=False)
    op.create_index(op.f('ix_college_applications_id'), 'college_applications', ['id'], unique=False)
    op.create_index(op.f('ix_college_applications_status'), 'college_applications', ['status'], unique=False)
    op.create_table('enrollment_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipeds_id', sa.Integer(), nullable=False, comment='IPEDS institution identifier'),
    sa.Column('academic_year', sa.String(length=10), nullable=False, comment='Academic year (e.g., 2023-24)'),
    sa.Column('total_enrollment', sa.Integer(), nullable=True, comment='Total undergraduate enrollment'),
    sa.Column('full_time_enrollment', sa.Integer(), nullable=True, comment='Full-time undergraduate enrollment'),
    sa.Column('part_time_enrollment', sa.Integer(), nullable=True, comment='Part-time undergraduate enrollment'),
    sa.Column('enrollment_men', sa.Integer(), nullable=True, comment='Number of male students enrolled'),
    sa.Column('enrollment_women', sa.Integer(), nullable=True, comment='Number of female students enrolled'),
    sa.Column('enrollment_in_state', sa.Integer(), nullable=True, comment='Number of in-state students'),
    sa.Column('enrollment_out_of_state', sa.Integer(), nullable=True, comment='Number of out-of-state students'),
    sa.Column('percent_full_time', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage of students enrolled full-time'),
    sa.Column('percent_in_state', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage of students from in-state'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['ipeds_id'], ['institutions.ipeds_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Enrollment statistics by academic year'
    )
    op.create_index(op.f('ix_enrollment_data_academic_year'), 'enrollment_data', ['academic_year'], unique=False)
    op.create_index(op.f('ix_enrollment_data_id'), 'enrollment_data', ['id'], unique=False)
    op.create_index(op.f('ix_enrollment_data_ipeds_id'), 'enrollment_data', ['ipeds_id'], unique=False)
    op.create_index(op.f('ix_enrollment_data_total_enrollment'), 'enrollment_data', ['total_enrollment'], unique=False)
    op.create_table('graduation_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipeds_id', sa.Integer(), nullable=False, comment='IPEDS institution identifier'),
    sa.Column('cohort_year', sa.String(length=10), nullable=False, comment='Starting cohort year (e.g., 2017 for 6-year rate in 2023)'),
    sa.Column('retention_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='First-year retention rate (percentage)'),
    sa.Column('graduation_rate_4_year', sa.Numeric(precision=5, scale=2), nullable=True, comment='4-year graduation rate (percentage)'),
    sa.Column('graduation_rate_6_year', sa.Numeric(precision=5, scale=2), nullable=True, comment='6-year graduation rate (percentage)'),
    sa.Column('graduation_rate_8_year', sa.Numeric(precision=5, scale=2), nullable=True, comment='8-year graduation rate (percentage)'),
    sa.Column('cohort_size', sa.Integer(), nullable=True, comment='Size of the entering cohort'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['ipeds_id'], ['institutions.ipeds_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Graduation and retention rates by cohort year'
    )
    op.create_index(op.f('ix_graduation_data_cohort_year'), 'graduation_data', ['cohort_year'], unique=False)
    op.create_index(op.f('ix_graduation_data_graduation_rate_6_year'), 'graduation_data', ['graduation_rate_6_year'], unique=False)
    op.create_index(op.f('ix_graduation_data_id'), 'graduation_data', ['id'], unique=False)
    op.create_index(op.f('ix_graduation_data_ipeds_id'), 'graduation_data', ['ipeds_id'], unique=False)
    op.create_index(op.f('ix_graduation_data_retention_rate'), 'graduation_data', ['retention_rate'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_accounts_id'), 'oauth_accounts', ['id'], unique=False)
    op.create_table('scholarship_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INTERESTED', 'PLANNING', 'IN_PROGRESS', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'NOT_PURSUING', name='applicationstatus'), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('essay_draft', sa.Text(), nullable=True),
    sa.Column('documents_needed', sa.Text(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('award_amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_scholarship', 'scholarship_applications', ['user_id', 'scholarship_id'], unique=True)
    op.create_index('idx_user_status', 'scholarship_applications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_scholarship_applications_id'), 'scholarship_applications', ['id'], unique=False)
    op.create_index(op.f('ix_scholarship_applications_status'), 'scholarship_applications', ['status'], unique=False)
    op.create_table('tuition_data',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('institution_id', sa.Integer(), nullable=False, comment='Direct foreign key to institutions.id'),
    sa.Column('ipeds_id', sa.Integer(), nullable=False, comment='Institution IPEDS ID (foreign key)'),
    sa.Column('academic_year', sa.String(length=10), nullable=False, comment='Academic year (e.g., "2025-26")'),
    sa.Column('data_source', sa.String(length=500), nullable=False, comment='Source of the data (e.g., "https://...")'),
    sa.Column('tuition_in_state', sa.Numeric(precision=10, scale=2), nullable=True, comment='In-state tuition cost'),
    sa.Column('tuition_out_state', sa.Numeric(precision=10, scale=2), nullable=True, comment='Out-of-state tuition cost'),
    sa.Column('required_fees_in_state', sa.Numeric(precision=10, scale=2), nullable=True, comment='Required fees for in-state students'),
    sa.Column('required_fees_out_state', sa.Numeric(precision=10, scale=2), nullable=True, comment='Required fees for out-of-state students'),
    sa.Column('room_board_on_campus', sa.Numeric(precision=10, scale=2), nullable=True, comment='Room and board costs on campus'),
    sa.Column('is_admin_verified', sa.Boolean(), nullable=False, comment='True if admin has verified/updated this data via CampusConnect'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ipeds_id'], ['institutions.ipeds_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipeds_id', 'academic_year', 'data_source', name='uq_tuition_institution_year_source'),
    comment='Tuition and financial data for institutions'
    )
    op.create_index(op.f('ix_tuition_data_academic_year'), 'tuition_data', ['academic_year'], unique=False)
    op.create_index(op.f('ix_tuition_data_data_source'), 'tuition_data', ['data_source'], unique=False)
    op.create_index(op.f('ix_tuition_data_id'), 'tuition_data', ['id'], unique=False)
    op.create_index(op.f('ix_tuition_data_institution_id'), 'tuition_data', ['institution_id'], unique=False)
    op.create_index(op.f('ix_tuition_data_ipeds_id'), 'tuition_data', ['ipeds_id'], unique=False)
    op.create_index(op.f('ix_tuition_data_tuition_in_state'), 'tuition_data', ['tuition_in_state'], unique=False)
    op.create_index(op.f('ix_tuition_data_tuition_out_state'), 'tuition_data', ['tuition_out_state'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('high_school_name', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('gpa_scale', sa.String(length=20), nullable=True),
    sa.Column('sat_score', sa.Integer(), nullable=True),
    sa.Column('act_score', sa.Integer(), nullable=True),
    sa.Column('intended_major', sa.String(length=255), nullable=True),
    sa.Column('career_goals', sa.String(length=500), nullable=True),
    sa.Column('volunteer_hours', sa.Integer(), nullable=True),
    sa.Column('extracurriculars', sa.JSON(), nullable=True),
    sa.Column('work_experience', sa.JSON(), nullable=True),
    sa.Column('honors_awards', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('location_preference', sa.String(length=2), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{"confetti_enabled": true}', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_graduation_year'), 'user_profiles', ['graduation_year'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_location_preference'), 'user_profiles', ['location_preference'], unique=False)
    op.create_index(op.f('ix_user_profiles_state'), 'user_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_state'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_location_preference'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_graduation_year'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_tuition_data_tuition_out_state'), table_name='tuition_data')
    op.drop_index(op.f('ix_tuition_data_tuition_in_state'), table_name='tuition_data')
    op.drop_index(op.f('ix_tuition_data_ipeds_id'), table_name='tuition_data')
    op.drop_index(op.f('ix_tuition_data_institution_id'), table_name='tuition_data')
    op.drop_index(op.f('ix_tuition_data_id'), table_name='tuition_data')
    op.drop_index(op.f('ix_tuition_data_data_source'), table_name='tuition_data')
    op.drop_index(op.f('ix_tuition_data_academic_year'), table_name='tuition_data')
    op.drop_table('tuition_data')
    op.drop_index(op.f('ix_scholarship_applications_status'), table_name='scholarship_applications')
    op.drop_index(op.f('ix_scholarship_applications_id'), table_name='scholarship_applications')
    op.drop_index('idx_user_status', table_name='scholarship_applications')
    op.drop_index('idx_user_scholarship', table_name='scholarship_applications')
    op.drop_table('scholarship_applications')
    op.drop_index(op.f('ix_oauth_accounts_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_graduation_data_retention_rate'), table_name='graduation_data')
    op.drop_index(op.f('ix_graduation_data_ipeds_id'), table_name='graduation_data')
    op.drop_index(op.f('ix_graduation_data_id'), table_name='graduation_data')
    op.drop_index(op.f('ix_graduation_data_graduation_rate_6_year'), table_name='graduation_data')
    op.drop_index(op.f('ix_graduation_data_cohort_year'), table_name='graduation_data')
    op.drop_table('graduation_data')
    op.drop_index(op.f('ix_enrollment_data_total_enrollment'), table_name='enrollment_data')
    op.drop_index(op.f('ix_enrollment_data_ipeds_id'), table_name='enrollment_data')
    op.drop_index(op.f('ix_enrollment_data_id'), table_name='enrollment_data')
    op.drop_index(op.f('ix_enrollment_data_academic_year'), table_name='enrollment_data')
    op.drop_table('enrollment_data')
    op.drop_index(op.f('ix_college_applications_status'), table_name='college_applications')
    op.drop_index(op.f('ix_college_applications_id'), table_name='college_applications')
    op.drop_index(op.f('ix_college_applications_deadline'), table_name='college_applications')
    op.drop_index('idx_user_institution', table_name='college_applications')
    op.drop_index('idx_user_college_status', table_name='college_applications')
    op.drop_index('idx_deadline', table_name='college_applications')
    op.drop_table('college_applications')
    op.drop_index(op.f('ix_admissions_data_sat_math_50th'), table_name='admissions_data')
    op.drop_index(op.f('ix_admissions_data_ipeds_id'), table_name='admissions_data')
    op.drop_index(op.f('ix_admissions_data_institution_id'), table_name='admissions_data')
    op.drop_index(op.f('ix_admissions_data_id'), table_name='admissions_data')
    op.drop_index(op.f('ix_admissions_data_acceptance_rate'), table_name='admissions_data')
    op.drop_index(op.f('ix_admissions_data_academic_year'), table_name='admissions_data')
    op.drop_table('admissions_data')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scholarships_title'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_scholarship_type'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_organization'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_deadline'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_id'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_institutions_student_faculty_ratio'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_state'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_size_category'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_ipeds_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_control_type'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_city'), table_name='institutions')
    op.drop_index('idx_institution_state_city', table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
